name = input("Enter a name: ")
adjective = input("Enter an adjective: ")
name_of_animal = input("Enter a name of animal: ")
place = input("Enter a place: ")
adjective_2 = input("Enter an adjective 2: ")
object = input("Enter an object: ")
verb_2 = input("Enter a verb 2: ")
exclamation = input("Enter an exclamation: ")
verb_past_tense = input("Enter a verb past tense: ")
adjective_3 = input("Enter an adjective 3. ")
print("One day, " + name + " and their " + adjective)
print(name_of_animal + " decided to explore the " + place + ". Suddenly, they found a " + adjective_2)
print(object + " that started")
print(verb_2 + "! shocked, " + name + " yelled,")
print(exclamation + "! but the " + name_of_animal)
print("just " + verb_past_tense + " away.")
print("In the end, they discovered it was all just a " + adjective_3 + " dream.")